sil18_vitrine_homepage:
    path:     /
    defaults: { _controller: sil18VitrineBundle:Default:index }

accueil:
    path:     /acceuil/{name}
    defaults: { _controller: sil18VitrineBundle:Default:index, name: visiteur }
    
mentions:
    path:     /mentions
    defaults: { _controller: sil18VitrineBundle:Default:mentions }