sil18\VitrineBundle\Entity\CategorieArticle:
    type: entity
    table: categorieArticle
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name: 
            type: string
            length: 100
    
    oneToMany:
        articles:
            targetEntity: Article
            mappedBy: categorieArticle
