sil18\VitrineBundle\Entity\Client:
    type: entity
    table: client
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        nom: 
            type: string
            length: 100
        
        prenom:
            type: string
            length: 100
        
        email:
            type: string
            length: 255
    
    oneToMany:
        commandes:
            targetEntity: Commande
            mappedBy: client
